#!/bin/bash
# run_caver.sh — Run CAVER 3.0.3 on a single PDB and emit a JSON summary.
#
# CAVER is the gold-standard tunnel-analysis tool. It is too slow for inline
# use (1-10 s/PDB), so we keep it offline-only for validation of top designs.
# For inline metrics, use src/protein_chisel/tools/tunnel_metrics.py.
#
# Usage:
#   run_caver.sh --pdb PATH --out_dir DIR \
#                ( --start_x X --start_y Y --start_z Z
#                | --catres_resnos 60,64,128,132,157 [--chain A] )
#                [--min_probe_radius 0.9]
#                [--shell_radius 3] [--shell_depth 4]
#
# Exit codes: 0 ok, 1 usage error, 2 CAVER failed, 3 no tunnels found.

set -euo pipefail

CAVER_HOME="${CAVER_HOME:-/net/software/lab/CAVER/caver_3.0.3/caver}"
JAVA="${JAVA:-/usr/bin/java}"
JAVA_HEAP="${CAVER_JAVA_HEAP:-4g}"

usage() {
    sed -n '2,16p' "$0" >&2
    exit 1
}

# ---- Parse args ----
PDB=""
OUT_DIR=""
START_X=""; START_Y=""; START_Z=""
CATRES=""
CHAIN="A"
PROBE="0.9"
SHELL_RADIUS="3"
SHELL_DEPTH="4"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --pdb)               PDB="$2";        shift 2;;
        --out_dir)           OUT_DIR="$2";    shift 2;;
        --start_x)           START_X="$2";    shift 2;;
        --start_y)           START_Y="$2";    shift 2;;
        --start_z)           START_Z="$2";    shift 2;;
        --catres_resnos)     CATRES="$2";     shift 2;;
        --chain)             CHAIN="$2";      shift 2;;
        --min_probe_radius)  PROBE="$2";      shift 2;;
        --shell_radius)      SHELL_RADIUS="$2"; shift 2;;
        --shell_depth)       SHELL_DEPTH="$2";  shift 2;;
        -h|--help)           usage;;
        *) echo "Unknown arg: $1" >&2; usage;;
    esac
done

[[ -z "$PDB" || -z "$OUT_DIR" ]] && usage
[[ ! -f "$PDB" ]] && { echo "PDB not found: $PDB" >&2; exit 1; }
[[ ! -d "$CAVER_HOME" ]] && { echo "CAVER_HOME not a dir: $CAVER_HOME" >&2; exit 2; }
command -v "$JAVA" >/dev/null 2>&1 || { echo "java not found: $JAVA" >&2; exit 2; }

# ---- Resolve starting point ----
if [[ -z "$START_X" ]]; then
    [[ -z "$CATRES" ]] && { echo "Need --start_x/y/z OR --catres_resnos" >&2; usage; }
    read -r START_X START_Y START_Z < <(python3 - "$PDB" "$CHAIN" "$CATRES" <<'PY'
import sys
pdb_path, chain, catres_str = sys.argv[1], sys.argv[2], sys.argv[3]
catres = {int(x) for x in catres_str.split(",") if x.strip()}
xs, ys, zs = [], [], []
with open(pdb_path) as f:
    for line in f:
        if line.startswith("ATOM") and line[12:16].strip() == "CA" and line[21] == chain:
            try:
                resi = int(line[22:26])
            except ValueError:
                continue
            if resi in catres:
                xs.append(float(line[30:38]))
                ys.append(float(line[38:46]))
                zs.append(float(line[46:54]))
n = len(xs)
if n == 0:
    sys.stderr.write(f"No CA atoms found for chain {chain} catres {catres}\n")
    sys.exit(2)
print(f"{sum(xs)/n:.4f} {sum(ys)/n:.4f} {sum(zs)/n:.4f}")
PY
)
fi

# ---- Stage workspace (CAVER wants a directory of PDBs) ----
mkdir -p "$OUT_DIR"
WORK="$(mktemp -d -t caver_XXXXXX)"
trap 'rm -rf "$WORK"' EXIT
mkdir -p "$WORK/pdbs"
PDB_BASE="$(basename "$PDB" .pdb)"
cp "$PDB" "$WORK/pdbs/${PDB_BASE}.pdb"

CONF="$WORK/config.txt"
cat > "$CONF" <<EOF
# Auto-generated by run_caver.sh
load_tunnels no
load_cluster_tree no
time_sparsity 1
first_frame 1
last_frame 1

starting_point_coordinates $START_X $START_Y $START_Z
probe_radius $PROBE
shell_radius $SHELL_RADIUS
shell_depth $SHELL_DEPTH

clustering average_link
weighting_coefficient 1
clustering_threshold 3.5

one_tunnel_in_snapshot cheapest
save_dynamics_visualization no

generate_summary yes
generate_tunnel_characteristics yes
generate_tunnel_profiles yes
generate_histograms no
generate_bottleneck_heat_map no
generate_profile_heat_map no

compute_tunnel_residues yes
residue_contact_distance 3.0
compute_bottleneck_residues yes
bottleneck_contact_distance 3.0

number_of_approximating_balls 12
compute_errors no
save_error_profiles no
generate_trajectory no

swap no
seed 1
EOF

# ---- Run CAVER ----
LOG="$OUT_DIR/caver_run.log"
T0=$(date +%s.%N)
set +e
"$JAVA" -Xmx"$JAVA_HEAP" -cp "$CAVER_HOME/lib" -jar "$CAVER_HOME/caver.jar" \
    -home "$CAVER_HOME" -pdb "$WORK/pdbs" -conf "$CONF" -out "$OUT_DIR" \
    > "$LOG" 2>&1
RC=$?
set -e
T1=$(date +%s.%N)
WALL=$(awk -v a="$T1" -v b="$T0" 'BEGIN{printf "%.3f", a-b}')

if [[ $RC -ne 0 ]]; then
    echo "{\"status\":\"caver_failed\",\"return_code\":$RC,\"wall_time_s\":$WALL,\"log\":\"$LOG\"}"
    exit 2
fi

# ---- Parse outputs into JSON summary ----
TC="$OUT_DIR/analysis/tunnel_characteristics.csv"
[[ ! -f "$TC" ]] && {
    echo "{\"status\":\"no_tunnels\",\"wall_time_s\":$WALL,\"log\":\"$LOG\"}"
    exit 3
}

python3 - "$TC" "$WALL" "$START_X" "$START_Y" "$START_Z" "$PROBE" <<'PY'
import csv, json, sys, math
tc, wall, sx, sy, sz, probe = sys.argv[1:]
rows = []
with open(tc) as f:
    reader = csv.reader(f)
    header = [h.strip() for h in next(reader)]
    for r in reader:
        if len(r) < len(header) or not r[0].strip():
            continue
        rec = dict(zip(header, [c.strip() for c in r]))
        try:
            rec["Bottleneck radius"] = float(rec["Bottleneck radius"])
            rec["Length"] = float(rec["Length"])
            rec["Throughput"] = float(rec["Throughput"])
            rec["Curvature"] = float(rec.get("Curvature", "nan") or "nan")
        except (ValueError, KeyError):
            continue
        rows.append(rec)

summary = {
    "status": "ok" if rows else "no_tunnels",
    "wall_time_s": float(wall),
    "n_tunnels": len(rows),
    "starting_point": [float(sx), float(sy), float(sz)],
    "min_probe_radius": float(probe),
}
if rows:
    narrowest = min(rows, key=lambda r: r["Bottleneck radius"])
    longest   = max(rows, key=lambda r: r["Length"])
    best_tp   = max(rows, key=lambda r: r["Throughput"])
    summary["narrowest_bottleneck_radius"] = narrowest["Bottleneck radius"]
    summary["narrowest_tunnel_id"]         = narrowest.get("Tunnel", "")
    summary["longest_tunnel_length"]       = longest["Length"]
    summary["longest_tunnel_id"]           = longest.get("Tunnel", "")
    summary["best_throughput"]             = best_tp["Throughput"]
    summary["tunnels"] = [
        {
            "id": r.get("Tunnel", ""),
            "cluster": r.get("Tunnel cluster", ""),
            "bottleneck_radius": r["Bottleneck radius"],
            "length": r["Length"],
            "throughput": r["Throughput"],
            "curvature": r["Curvature"],
        }
        for r in rows
    ]
print(json.dumps(summary, indent=2))
PY
